name: Quarterly Release
on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    steps:
      -  uses: ph-fritsche/action-dispatch@v1
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           ident: cd.yaml
           payload: '{}'
